In [68]:
import numpy as np
import pandas as pd

In [69]:
data =pd.read_csv('seed_data.csv')

In [70]:
data.head()

area  perimeter  compactness  length  width  asymmetry  \
0  15.26      14.84       0.8710   5.763  3.312      2.221   
1  14.88      14.57       0.8811   5.554  3.333      1.018   
2  14.29      14.09       0.9050   5.291  3.337      2.699   
3  13.84      13.94       0.8955   5.324  3.379      2.259   
4  16.14      14.99       0.9034   5.658  3.562      1.355   

   length_kernel_groove  kernel  
0                 5.220       0  
1                 4.956       0  
2                 4.825       0  
3                 4.805       0  
4                 5.175       0

In [71]:
data['kernel'].unique()

array([0, 1, 2], dtype=int64)

In [72]:
data['kernel'].value_counts()

2    70
1    70
0    70
Name: kernel, dtype: int64

In [73]:
x=data.drop(['kernel'],axis=1)
x

area  perimeter  compactness  length  width  asymmetry  \
0    15.26      14.84       0.8710   5.763  3.312      2.221   
1    14.88      14.57       0.8811   5.554  3.333      1.018   
2    14.29      14.09       0.9050   5.291  3.337      2.699   
3    13.84      13.94       0.8955   5.324  3.379      2.259   
4    16.14      14.99       0.9034   5.658  3.562      1.355   
..     ...        ...          ...     ...    ...        ...   
205  12.19      13.20       0.8783   5.137  2.981      3.631   
206  11.23      12.88       0.8511   5.140  2.795      4.325   
207  13.20      13.66       0.8883   5.236  3.232      8.315   
208  11.84      13.21       0.8521   5.175  2.836      3.598   
209  12.30      13.34       0.8684   5.243  2.974      5.637   

     length_kernel_groove  
0                   5.220  
1                   4.956  
2                   4.825  
3                   4.805  
4                   5.175  
..                    ...  
205                 4.870  
206                 5.003  
207                 5.056  
208                 5.044  
209                 5.063  

[210 rows x 7 columns]

In [74]:
y=data['kernel']
y

0      0
1      0
2      0
3      0
4      0
      ..
205    2
206    2
207    2
208    2
209    2
Name: kernel, Length: 210, dtype: int64

In [87]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

## Scaling the data

In [76]:
from sklearn.preprocessing import StandardScaler

In [101]:
scaler=StandardScaler()
x = scaler.fit_transform(x) 


In [102]:
## KNN Model

In [103]:
from sklearn.neighbors import KNeighborsClassifier

kn= KNeighborsClassifier(n_neighbors=3,p=2)
kn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [104]:
y_pred =kn.predict(x_test)
y_pred

array([0, 1, 0, 0, 2, 1, 1, 1, 1, 2, 0, 2, 0, 2, 1, 1, 2, 1, 0, 0, 2, 0,
       0, 0, 1, 1, 1, 0, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 0, 0, 2, 0, 1, 2,
       0, 1, 1, 0, 0, 1, 0, 1, 2], dtype=int64)

In [105]:
y_test

12     0
80     1
33     0
5      0
188    2
83     1
116    1
122    1
90     1
154    2
45     0
156    2
52     0
190    2
96     1
86     1
194    2
37     0
66     0
18     0
170    2
15     0
7      0
55     0
92     1
134    1
125    1
124    1
158    2
185    2
75     1
149    2
138    1
71     1
187    2
145    2
176    2
118    1
16     0
135    1
191    2
22     0
104    1
141    2
4      0
74     1
136    1
44     0
63     0
108    1
26     0
101    1
166    2
Name: kernel, dtype: int64

In [106]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 

In [107]:
confusion_matrix(y_pred,y_test)

array([[16,  2,  0],
       [ 1, 19,  0],
       [ 0,  0, 15]], dtype=int64)

In [108]:
accuracy_score(y_pred,y_test)

0.9433962264150944